apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users-deployment #prev postgres-customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user #prev postgres-customer
  template:
    metadata:
      labels:
        app: postgres-user #prev postgres-customer
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-users #postgres-customers
          env:
            - name: POSTGRESQL_USER
              value: dbuser
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: customer
          ports:
          - containerPort: 5433
            protocol: TCP