apiVersion: v1
kind: Service
metadata:
  name: postgres-user #prev postgres-customer
spec:
  type: ClusterIP
  ports:
  - port: 5433
    protocol: TCP
    targetPort: 5433
  selector:
    app: postgres-user #prev postgres-customer